"use client";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import store from "../features/store";
import { AppProvider } from "@/context";
import SpinnerLoading from "@/components/UI/SpinnerLoading";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <AppProvider>
            <Header />
            {children}
            <Footer />
          </AppProvider>
        </Provider>
      </body>
    </html>
  );
}
