"use client";

import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import store from "../features/store";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>
          {pathName !== "/login" && <Header />}
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
